### ISSUE TITLE
Update mod to be compatible with SotS DLC.

### ISSUE THREAD

**Issue by Jcat4609** [cjcocokrisp/GupRankings#1]
### Describe the Bug
The Gup Rankings leaderboard does not appear in game - however, the mod is loading, as can be seen in the RiskOfOptions menu.

### To Reproduce
Steps to reproduce the behaviour:
1. Load Risk of Rain with the Gup Rankings mod and all dependencies.
2. Enter a run with any survivor.

### Expected Behaviour
Leaderboard should appear on the right side of the screen

### Console Log
> [Error  : Unity Log] MissingMethodException: Method not found: UnityEngine.GameObject RoR2.Run.get_uiInstance()
Stack trace:
GupRankings.RankingDisplayHooks.RankingDisplay.Update (System.Action`1[T] orig, RoR2.UI.ObjectivePanelController self) (at /home/runner/work/GupRankings/GupRankings/GupRankings/RankingDisplayHooks/RankingDisplay.cs:53)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<RoR2.UI.ObjectivePanelController::Update>?1373018588(RoR2.UI.ObjectivePanelController)

Full log is attached (Please note that the error applies nearly every frame - thus the log has been bloated)
[LogOutput.log](https://github.com/user-attachments/files/16841531/LogOutput.log)

**Comment by cjcocokrisp** [comment]
Mods broke with the expansion. Haven't been following modding stuff since the dlc dropped since I just moved back into school this week so I just need to update it. Just did some research and it looks like I will probably be able to update it. If I find some time this week I'll get it updated if not I'll have it updated by Sunday the latest.

**Comment by cjcocokrisp** [comment]
Mod should be updated now and published to the Thunderstore. Let me know if you encounter any other issues and I hope you enjoy the mod!
